server:
  port: 8080
  servlet:
    context-path: /
spring:
  devtools:
    restart:
      enabled: true #开启热部署
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: lishuang001219
    hikari:
      minimum-idle: 5 #最小空闲连接数
      maximum-pool-size: 15 #最大连接数，默认10
      auto-commit: true #自动提交，默认true
      idle-timeout: 30000 #空闲连接存活最大时间，默认600000(10分钟)
      pool-name: BaojiaHikariCP #连接池名称
      max-lifetime: 1800000 #最长生命周期，默认1800000(30分钟)，0表示无限生命周期
      connection-timeout: 30000 #连接超时时间，默认30秒
      connection-test-query: SELECT 1 #连接测试查询
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.xlhj.baojia.entity
logging:
  config: classpath:logback-spring.xml
  level:
    com.xlhj.baojia: debug

jwt:
  header: Authorization
  tokenSecret: qazxswedcvfrtgbnhyujmkiolp #密钥
  tokenExpired: 3600000 #token过期时间(30分钟)